---
# tasks file for launch_oscap_scan
- name: Check update for security
  command: /bin/dnf check-update --security
  args:
    warn: no
  become: yes
  register: check_update
  failed_when: check_update.rc == 1
  changed_when: check_update.rc == 100
  until: check_update is not failed
  retries: 5

- debug:
    var: check_update

#- name: Create new incidentii
#  servicenow.itsm.incident:ii
#    instance:ii
#      username: "{{ snow_username }}"ii
#      password: "{{ snow_password }}"ii
#      host: "{{ snow_instance }}"ii
#    state: newii
#    short_description: Basic test incidentii

#- name: set_mitigation
#  set_fact:
#    mitigate: true
#  when: scan_score | float <= scan_threshold | float
#
#- name: SERVICENOW IF CHANGED
#  block:
#    - name: CREATE AN INCIDENT
#      snow_record:
#        username: "{{ snow_username }}"
#        password: "{{ snow_password }}"
#        instance: "{{ snow_instance }}"
#        state: present
#        table: incident
#        data:
#          short_description: "OSPP COMPLIANCE - below threshold - ON {{inventory_hostname}}"
#          severity: 3
#          priority: 2
#          caller_id: "System Administrator"
#          comments: "The configuration:\n--------\n OSPP COMPLIANCE \n--------\n is below 85% on {{inventory_hostname}}"
#      register: snow_var
#      delegate_to: localhost
#
#    - name: DEBUG SNOW_VAR
#      debug:
#        var: snow_var.record.number
#  when: mitigate|bool and snow_call|bool
